services:
  postgres:
    image: postgres:15
    container_name: task-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  task-service:
    image: ${DOCKERHUB_USERNAME}/task-service:latest
    container_name: task-service
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  mail-service:
    image: ${DOCKERHUB_USERNAME}/mail-service:latest
    container_name: mail-service
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - task-service
      - mail-service
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config: